apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: flask-app
        image: robertxd98/flask-app:0.0.2
        ports:
        - containerPort: 5000
          name: flask-app
